CookBookMVC.Web/Controllers/RecipeController.cs
using CookBookMVC.Application.Interfaces;
using System.Linq;
using CookBookMVC.Application.ViewModels.Recipe;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using CookBookMVC.Application.ViewModels.Time;
using CookBookMVC.Domain.Model;


namespace CookBookMVC.Web.Controllers
{
	public class RecipeController : Controller
	{
		private readonly IRecipeService _recipeService;
		private readonly ICategoryService _categoryService;
		private readonly IDifficultyService _difficultyService;
		private readonly ITimeService _timeService;
		private readonly IIngredientService _ingredientService;
		public RecipeController(IRecipeService recipeService,
			ICategoryService categoryService, 
			IDifficultyService difficultyService, 
			ITimeService timeService,
			IIngredientService ingredientService)
		{
			_recipeService = recipeService;
			_categoryService = categoryService;
			_difficultyService = difficultyService;
			_timeService = timeService;
			_ingredientService = ingredientService;
		}

		[HttpGet]
		public IActionResult Index()
		{
			//utworzyć widok dla tej akcji
			//tabela z przepisami
			//filtrowanie przepisów
			//przygotować dane
			//przekazać filtry do serwisu
			//serwis musi przygotować 
			//serwis musi zwrócić dane w odpowiednim formacie
			var model = _recipeService.GetAllRecipesForList(20, 1, "");
			return View(model);
		}

		[HttpPost]
		public IActionResult Index(int pageSize, int? pageNo, string searchString)
		{
			if (!pageNo.HasValue)
			{
				pageNo = 1;
			}
			if (searchString is null)
			{
				searchString = string.Empty;
			}
			var model = _recipeService.GetAllRecipesForList(pageSize, (int)pageNo, searchString);
			return View(model);
		}

		[HttpGet]
		public IActionResult AddRecipe()
		{
			FillViewBags();
			return View(new NewRecipeVm());
		}

		[HttpPost]
		public IActionResult AddRecipe(NewRecipeVm model)
		{
			if (ModelState.IsValid)
			{
				if (model.TimeId.HasValue)
				{
					var selectedTime = _timeService.GetTimeById((int)model.TimeId);
					if (selectedTime != null)
					{
						model.TimeAmount = selectedTime.Amount;
						model.TimeUnit = selectedTime.Unit;
					}
				}
				else
				if (model.TimeAmount != 0 && !string.IsNullOrEmpty(model.TimeUnit))
				{
					var newTime = new TimeForListVm
					{
						Amount = (int)model.TimeAmount,
						Unit = model.TimeUnit
					};
					model.TimeId = _timeService.AddTimeToRecipe(newTime);
				}
				else
				{
					ModelState.AddModelError("", "You must provide new time: Amount and Unit or both");
					FillViewBags();
					return View(model);
				}
				if (model.IngredientsWithQuantity != null)
                    foreach (var ingredient in model.IngredientsWithQuantity)
                    {
                        var selectedIngredient = _ingredientService.GetIngredientById(ingredient.IngredientId);

                    }
                
					var id = _recipeService.AddRecipe(model);
				return RedirectToAction("Index");
				
			}
			else { Console.WriteLine(Console.Error); }	
			
			// test	
			FillViewBags();
			return View(model);
		}

		[HttpGet]
		public IActionResult ViewRecipeDetails(int id)
		{
			var recipeModel = _recipeService.GetRecipeDetails(id);
			if (recipeModel == null)
			{
				return View("Error");
			}
			return View(recipeModel);
		}
		public void FillViewBags()
		{
			var categoryListVm = _categoryService.GetListCategoryForList();
			ViewBag.Categories = categoryListVm.Categories.Select(categ => new SelectListItem
			{
				Value = categ.Id.ToString(),
				Text = categ.Name
			}).ToList();
			foreach (var item in ViewBag.Categories)
			{
				Console.WriteLine($"Category: {item.Text}, Value: {item.Value}");
			}
			var difficultyListVm = _difficultyService.GetListDifficultyForList();
			ViewBag.Difficulties = difficultyListVm.Difficulties.Select(diff => new SelectListItem
			{
				Value = diff.Id.ToString(),
				Text = diff.Name
			}).ToList();
			foreach (var item in ViewBag.Difficulties)
			{
				Console.WriteLine($"Difficulty: {item.Text}, Value: {item.Value}");
			}
			var timeListVm = _timeService.GetListTimeForList();
			ViewBag.Times = timeListVm.Times.Select(tim => new SelectListItem
				{
					Value = tim.Id.ToString(),
					Text = tim.Amount.ToString() + " " + tim.Unit
				});
			foreach (var item in ViewBag.Times)
			{
				Console.WriteLine($"Time: {item.Text}, Value: {item.Value}");
			}
			var ingredientListVm = _ingredientService.GetAllIngredients();
			ViewBag.Ingredients = ingredientListVm.Ingredients.Select(ing => new SelectListItem
			{
				Value = ing.Id.ToString(),
				Text = ing.Name + " " + ing.Unit
			});
		}

	}
}

CookBookMVC.Web/Views/Recipe/AddRecipe.cshtml
@model CookBookMVC.Application.ViewModels.Recipe.NewRecipeVm

@{
	ViewData["Title"] = "AddRecipe";
}

<h1>AddRecipe</h1>

<h4>NewRecipeVm</h4>
<hr />
<div class="row">
	<div class="col-md-12">
		<form asp-action="AddRecipe">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>

			<input type="hidden" asp-for="Id" />

			<div class="form-group">
				<label asp-for="Name" class="control-label"></label>
				<input asp-for="Name" class="form-control" />
				<span asp-validation-for="Name" class="text-danger"></span>
			</div>

			<div class="form-group">
				<label asp-for="CategoryId" class="control-label"></label>
				@* Użyj DropDownList dla kategorii *@
				<select asp-for="CategoryId" class="form-control" asp-items="ViewBag.Categories"></select>
				<span asp-validation-for="CategoryId" class="text-danger"></span>
			</div>
			
			<div class="form-group">
				<label asp-for="AmountOfIngredients" class="control-label"></label>
				<input asp-for="AmountOfIngredients" class="form-control" id="amountOfIngredients" />
				<span asp-validation-for="AmountOfIngredients" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label>Ingredients</label>
				<div class="row" id="ingredient-container" </div>
			</div>
			<div class="form-group">
				<label asp-for="DifficultyId" class="control-label"></label>
				@*Użyj DropDownList dla trudnosci*@
				<select asp-for="DifficultyId" class="form-control" asp-items="ViewBag.Difficulties"></select>
				<span asp-validation-for="DifficultyId" class="text-danger"></span>
			</div>

			<div class="form-group">
				<label asp-for="TimeId" class="control-label"></label>
				<select asp-for="TimeId" class="form-control" id="time-dropdown">
					<option value="">Select existing time</option>
					@foreach (var time in ViewBag.Times)
					{
						<option value="@time.Value">@time.Text</option>
					}
				</select>
				@*<span asp-validation-for="TimeId" class="text-danger"></span>*@
			</div>


			<div class="form-group" id="new-time-fields" style="display: none;">
				<label asp-for="TimeAmount" class="control-label">Amount:</label>
				<input asp-for="TimeAmount" class="form-control" />
				@*<span asp-validation-for="TimeAmount" class="text-danger"></span>*@

				<label asp-for="TimeUnit" class="control-label">Unit:</label>
				<input asp-for="TimeUnit" class="form-control" />
				@*<span asp-validation-for="TimeUnit" class="text-danger"></span>*@
			</div>


			<button type="button" class="btn btn-primary" id="show-new-time-fields">Add New Time</button>

			@*await Html.PartialAsync("_NewTimeAdd", Model)
	*@
			<div class="form-group">
				<label asp-for="Description" class="control-label"></label>
				<input asp-for="Description" class="form-control" />
				<span asp-validation-for="Description" class="text-danger"></span>
			</div>

			
			<div class="form-group mt-3">
				<input type="submit" value="Create" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Index">Back to List</a>
</div>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
	<script>
		// Funkcja dodająca nowe pola dla kolejnych składników, do zrobienia by wybierać z listy
		document.addEventListener("DOMContentLoaded", function () {
			document.getElementById("amountOfIngredients").addEventListener("input", function () {
				var amount = parseInt(this.value);
				var container = document.getElementById("ingredient-container");
				container.innerHTML = "";

				if (!isNaN(amount) && amount > 0) {
					for (var i = 0; i < amount; i++) {
						var newIngredientHtml = `
									<div class="row mb-2">
										<div class="col-md-6">
											<div class="ingredient">
												<label>Ingredient</label>
												<select name="IngredientsWithQuantity[${i}].IngredientId" class="form-control">
		@foreach (var item in ViewBag.Ingredients)
		{
															<option value="@item.Value">@item.Text</option>
		}
												</select>
												<span class="text-danger"></span>
											</div>
										</div>
										<div class="col-md-6">
											<div class="ingredient">
												<label>Quantity</label>
												<input name="IngredientsWithQuantity[${i}].Quantity" class="form-control" type="number" min="0" />
												<span class="text-danger"></span>
											</div>
										</div>
									</div>
								`;
						container.insertAdjacentHTML("beforeend", newIngredientHtml);
					}
				}
			});
		});
	</script>
<script type="text/javascript">
	$(window).on("load", function () {
		if ($("#time-dropdown").val() === "Select existing time") {
			$("#new-time-fields").show();
		} else {
			$("#new-time-fields").hide();
		}

		// Obsługa zmiany wartości w dropdownie
		$("#time-dropdown").change(function () {
			if ($(this).val() === "Select existing time") {
				$("#new-time-fields").show();
			} else {
				$("#new-time-fields").hide();
			}
		});

		// Obsługa kliknięcia przycisku
		$("#show-new-time-fields").click(function () {
			$("#new-time-fields").toggle();
		});
	});		
	</script>
}
	

CookBookMVC.Web/Views/Recipe/Index.cshtml
@model CookBookMVC.Application.ViewModels.Recipe.ListRecipeForListVm

@{
	ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
	<a asp-action="Create">Create New</a>
</p>
<form asp-action="Index" asp-controller="Recipe" method="post">
	<div class="row">
		<select asp-for="PageSize">
			<option value="1">1 recipe</option> @* dodane na potrzeby prezentacji *@
			<option value="5">5 recipes</option>
			<option value="10">10 recipes</option>
			<option value="20">20 recipes</option>
			<option value="30">30 recipes</option>
			<option value="50">50 recipes</option>
			<option value="100">100 recipes</option>
		</select>
		<input type="text" asp-for="SearchString" name="searchString" id="searchString" />
		<input type="submit" value="Wyszukaj" />
	</div>
	<div class="row">
		<table class="table">
			<thead>
				<tr>
					<th>
						Id
					</th>
					<th>
						Name
					</th>
					<th>
						Category
					</th>

				</tr>
			</thead>
			<tbody>
				@foreach (var item in Model.Recipes)
				{
					<tr>
						<td>
							@Html.DisplayFor(modelItem => item.Id)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.Name)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.Category)
						</td>

						<td>
							@Html.ActionLink("Edit", "Edit", new {  id=item.Id }) |
							@Html.ActionLink("Details", "Details", new { id = item.Id }) |
							@Html.ActionLink("Delete", "Delete", new { id=item.Id })
						</td>
					</tr>
				}
			</tbody>
		</table>
	</div>
	<div class="row">
		<table>
			<tr>
				@for (int i = 1; i <= Math.Ceiling(Model.Count / (double)Model.PageSize); i++)
				{
					<td>
						@if (i != Model.CurrentPage)
						{
							<a href="javascript:PagerClick(@i)">@i</a>
						}
						else
						{
							<span>@i</span>
						}
					</td>
				}
			</tr>
		</table>
		<input type="hidden" name="pageNo" id="pageNo" />
		<input type="hidden" name="pageSize" id="pageSize" value="1" />
	</div>
</form>
@section Scripts
{
	<script type="text/javascript">
		function PagerClick(index) {
			document.getElementById("pageNo").value = index;
			document.forms[0].submit();
		}	
	</script>
}

CookBookMVC.Web/Views/Recipe/ViewRecipeDetails.cshtml
@model CookBookMVC.Application.ViewModels.Recipe.RecipeDetailsVm

@{
	ViewData["Title"] = "ViewRecipeDetails";
}

<h1>ViewRecipeDetails</h1>

<div>
	<h4>ViewRecipeDetailsVm</h4>
	<hr />
	<dl class="row">
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Id)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Id)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Name)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Name)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.CategoryName)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.CategoryName)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.DifficultyName)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.DifficultyName)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.TimeName)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.TimeName)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Description)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Description)
		</dd>
	
	<h3>Ingredients (@Model.AmountOfIngredients):</h3>
			@Html.Partial("_IngredientList", Model.Ingredients)
	</dl>
</div>
<div>
	@Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
	<a asp-action="Index">Back to List</a>
</div>